### ISSUE TITLE
大佬，你好！可以按isbn定向去爬取吗？

### ISSUE THREAD

**Issue by GUI9527** [derek-s/CALIS_Spider#1]
不需要全部爬取，有很多没用的数据，可以按ISBN吗?就是先让python读取txt里的ISBN(每行一个ISBN)，这样就可以爬到自己需要的，不需要的不爬取

**Comment by derek-s** [comment]
本来就是读取isbn号再爬取的。

**Comment by GUI9527** [comment]
有测试直接存csv, 需要的数据不是太多，存csv就好了，c网中间那3个url不知道从哪找。

**Comment by derek-s** [comment]
这个就得你自己找一下了:)

**Comment by GUI9527** [comment]
开利事，之前用过其他方式的采集器，1天超过1000个isbn，会封ip，会封个几天，超过1000只能换几个ip采集。你用大蟒蛇尝试测试超过1000的吗？

**Comment by derek-s** [comment]
爬虫配备IP池应该算是正常操作的吧
