### ISSUE TITLE
你好，又来了

### ISSUE THREAD

**Issue by GUI9527** [derek-s/CALIS_Spider#2]
一直在研究你的calis代码，提取了oid，拼接成详情页的url, 在验证码页面和详情页之间的跳转逻辑，一直没研究明白，可否相告，想把代码转成win上运行，一直没成功

**Comment by derek-s** [comment]
> 一直在研究你的calis代码，提取了oid，拼接成详情页的url, 在验证码页面和详情页之间的跳转逻辑，一直没研究明白，可否相告，想把代码转成win上运行，一直没成功

出现验证码说明爬的速度过快。要解决嘛，找个代理池或者自建个代理池之类的，找个打码平台或者自己训练一个OCR识别也可以。
