### ISSUE TITLE
你好！验证码搞定了！还有一个问题请教你

### ISSUE THREAD

**Issue by pythonseleniumer** [derek-s/CALIS_Spider#3]
验证码验证没问题，就是返回500，这是什么鬼反爬手法，你多试几十条都成功下载了吗？我用selenium,搞定了，就是没搞会requests方法。您的代码我还剩最后一点没看懂，就是
s = requests.session()
s.get(calisUrl)

cookies = {“JSESSIONID“:passkey}
这个passkey不是在后面才出来啊，怎么传到前面来的呢？现在就是这个cookies没写，就返回500。不过手动的时候，也是返回500，要退回验证码页面，刷新一下，就到详情页了。

那个detaiArg可以一个xpath出来，可以不用切片
detaiArg = selector.xpath(“//input[@name='idxCheckBox']/@value“).get()

**Comment by derek-s** [comment]
没遇到过500，这个passkey是调用的时候手动填上去的哈哈哈。
